### ISSUE TITLE
`bundle exec devtools init` breaks

### ISSUE THREAD

**Issue by gtramontina** [mbj/devtools#67]
Running `bundle exec devtools init`, as specified in the Readme, fails with the following:

```
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/devtools-879c5d25fbf4/lib/devtools/site/initializer.rb:35:in `call': undefined method `sync' for #<Devtools::Site:0x007fae5a99c8b0> (NoMethodError)
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/devtools-879c5d25fbf4/lib/devtools/site/initializer.rb:10:in `call'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/devtools-879c5d25fbf4/lib/devtools/site.rb:35:in `init'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/devtools-879c5d25fbf4/lib/devtools.rb:94:in `init'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/devtools-879c5d25fbf4/bin/devtools:13:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/devtools:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin/devtools:23:in `<main>'
```

I'm using what's on `master` (`gem 'devtools', git: 'https://github.com/mbj/devtools.git'` – again, as instructed in the Readme).

Any clues?

**Comment by mbj** [comment]
@gtramontina Thats deprecated. I'll have to remove it from the README. Thx for creating the issue.

**Comment by gtramontina** [comment]
No problem. But how to proceed with getting `devtools` up and running?

**Comment by mbj** [comment]
This feature was dropped. The readme is upto date now. Closing.
